### ISSUE TITLE
documentation contains broken link to Configuration Generator

### ISSUE THREAD

**Issue by charlesmims** [rexray/rexray#1196] opened 2018-03-26 20:23 UTC
# Summary
Please enter a summary of the issue here.
In the documentation at http://rexray.readthedocs.io/en/stable/ a paragraph reads:
```
After REX-Ray has been installed, copy and paste the contents from the REX-Ray Configuration Generator to a new file on the host at /etc/rexray/config.yml. The configuration generator will satisfy the majority of use cases for REX-Ray.
```
In that paragraph, REX-Ray Configuration Generator is a broken link.

# Bug Reports
Summary description covers it, I think.

## Version
n/a - documentation.

## Expected Behavior
Link should work.

## Actual Behavior
404 Not Found: Requested route ('rexrayconfig.codedellemc.com') does not exist.

## Steps To Reproduce
Go to http://rexray.readthedocs.io/en/stable
Click the first link under "Configure" labeled "REX-Ray Configuration Generator".

## Configuration Files
 I wasn't able to generate configuration files because of this broken link.

**Comment by clintkitson** [comment] 2018-04-04 02:26
Hello @charlesmims,

We will get this link fixed.

https://github.com/rexray/rexray/issues/1178

**Comment by Getty** [comment] 2018-05-16 14:45
*bump*

**Comment by codenrhoden** [comment] 2018-05-17 16:08
Closing as duplicate of #1178

**Closed by codenrhoden** 2018-05-17 16:08 UTC
